# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 22:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0010_auto_20160725_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 22, 35, 8, 908226, tzinfo=utc)),
        ),
    ]
